# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'unirecycle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for unirecycle
  pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'RangeSeekSlider'
pod 'DropDown' 
pod 'NVActivityIndicatorView'

end
